Repository Madu-de/MaduChat, pull requests merged in 2023-10, with the labels that each got.

#91 Fix #88
  frontend/src/app/chat/message/message.component.html
  frontend/src/app/friends/user-list/user/user.component.html
  frontend/src/app/friends/user-list/user/user.component.spec.ts
  frontend/src/app/user/badge-list/badge-list.component.html
  frontend/src/app/user/badge-list/badge-list.component.scss
  frontend/src/app/user/badge-list/badge-list.component.spec.ts
  frontend/src/app/user/badge-list/badge-list.component.ts
  frontend/src/app/user/badge-list/mock-badge-list.component.ts
  frontend/src/app/user/user.component.html
  frontend/src/app/user/user.component.spec.ts
  frontend/src/app/user/user.module.ts
Labels: codechange

#93 Feature #92
  frontend/src/app/navigation/sidebar/edit-chat-popup/edit-chat-popup.component.html
  frontend/src/app/navigation/sidebar/edit-chat-popup/edit-chat-popup.component.spec.ts
  frontend/src/app/navigation/sidebar/edit-chat-popup/edit-chat-popup.component.ts
  frontend/src/app/services/languages/de.ts
  frontend/src/app/services/languages/en.ts
  frontend/src/app/services/languages/es.ts
  frontend/src/app/services/languages/fr.ts
  frontend/src/app/services/languages/language.interface.ts
Labels: enhancement

#96 Fix #94
  backend/src/chat/chat.ts
  frontend/src/app/navigation/sidebar/edit-chat-popup/edit-chat-popup.component.html
  frontend/src/app/navigation/sidebar/edit-chat-popup/edit-chat-popup.component.ts
Labels: bug

#97 Fix #95
  backend/src/chat/chat.service.ts
Labels: bug

#99 Fix #98
  backend/README.md
Labels: documentation

#104 Feature #103
  frontend/package.json
  frontend/src/app/navigation/header/header.component.html
  frontend/src/package.json
Labels: enhancement, codechange

#106 Fix #105
  frontend/src/app/chat/chat.component.ts
Labels: bug

#108 Version #107
  README.md
  backend/package-lock.json
  backend/package.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/package.json
Labels: enhancement, codechange

#112 Feature #110
  README.md
  backend/src/app.module.ts
Labels: documentation, enhancement

#121 Feature #3
  backend/.gitignore
  backend/README.md
  backend/package-lock.json
  backend/package.json
  backend/src/user/sharp.pipe.ts
  backend/src/user/user.controller.ts
  backend/src/user/user.service.ts
  backend/src/user/user.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/app.module.ts
  frontend/src/app/chat/message/message.component.spec.ts
  frontend/src/app/chat/message/message.component.ts
  frontend/src/app/friends/user-list/user/user.component.html
  frontend/src/app/friends/user-list/user/user.component.ts
  frontend/src/app/navigation/header/profile-popup/profile-popup.component.ts
  frontend/src/app/services/image.service.spec.ts
  frontend/src/app/services/image.service.ts
  frontend/src/app/services/languages/de.ts
  frontend/src/app/services/languages/en.ts
  frontend/src/app/services/languages/es.ts
  frontend/src/app/services/languages/fr.ts
  frontend/src/app/services/languages/language.interface.ts
  frontend/src/app/services/user.service.ts
  frontend/src/app/settings/option/option.component.ts
  frontend/src/app/settings/settings.component.html
  frontend/src/app/settings/settings.component.scss
  frontend/src/app/settings/settings.component.spec.ts
  frontend/src/app/settings/settings.component.ts
  frontend/src/app/settings/settings.module.ts
  frontend/src/app/settings/tab/category/category.component.html
  frontend/src/app/settings/tab/category/category.component.scss
  frontend/src/app/settings/tab/category/category.component.spec.ts
  frontend/src/app/settings/tab/category/category.component.ts
  frontend/src/app/settings/tab/general/general.component.html
  frontend/src/app/settings/tab/general/general.component.scss
  frontend/src/app/settings/tab/general/general.component.spec.ts
  frontend/src/app/settings/tab/general/general.component.ts
  frontend/src/app/settings/tab/profile/picture/picture.component.html
  frontend/src/app/settings/tab/profile/picture/picture.component.scss
  frontend/src/app/settings/tab/profile/picture/picture.component.spec.ts
  frontend/src/app/settings/tab/profile/picture/picture.component.ts
  frontend/src/app/settings/tab/profile/profile.component.html
  frontend/src/app/settings/tab/profile/profile.component.scss
  frontend/src/app/settings/tab/profile/profile.component.spec.ts
  frontend/src/app/settings/tab/profile/profile.component.ts
  frontend/src/app/settings/tab/tab.component.html
  frontend/src/app/settings/tab/tab.component.scss
  frontend/src/app/settings/tab/tab.component.spec.ts
  frontend/src/app/settings/tab/tab.component.ts
  frontend/src/app/user/user.component.html
  frontend/src/app/user/user.component.ts
  frontend/src/package.json
Labels: documentation, enhancement

#122 Fix #113
  backend/src/auth/auth.guard.ts
  backend/src/user/user.service.ts
Labels: bug

#130 Feature #128 Added docker files
  backend/.dockerignore
  backend/Dockerfile
  docker-compose.yml
  frontend/.dockerignore
  frontend/Dockerfile
  frontend/angular.json
Labels: enhancement

#132 docker cache/layers usage optimisation
  backend/Dockerfile
  frontend/Dockerfile
Labels: codechange

#135 Feature #129
  README.md
Labels: documentation

#136 Feature #109
  frontend/src/app/navigation/header/header.component.html
  frontend/src/app/navigation/header/header.component.ts
Labels: enhancement
